[deploy]
bucket = 'simplynaturell-cruddur-cfn-artifacts'
region = 'us-west-2'
stack_name = 'CrdCicd'

[parameters]
ServiceStack = 'CrdSrvBackendFlask'
ClusterStack = 'CrdCluster'
GitHubBranch = 'prd'
GithubRepo = 'aws-bootcamp-cruddur-2023'
ArtifactBucketName = "simplynaturell-cruddur-codepipeline-artifacts"